var regexObjs =[ {
    pattern: "(?s)\\s*ALERT:\\s?You\\'ve\\s+spent\\s+(?:Rs\\.?|INR)(?:\\s*)([0-9,]+(?:\\.[0-9]+)?|\\.[0-9]+)\\s+on\\s+[CcRrEeDdiITt]+\\s+[CaCArRdD]+\\s+([xX0-9]+)\\s+at\\s+([a-zA-Z0-9.,-@\\s]+)\\s+on\\s+(\\d{4}-\\d{2}-\\d{2}:\\d{2}:\\d{2}:\\d{2})\\.[AvlaVL]+\\s+[balanceBALANCE]+\\s+-\\s+(?:Rs\\.?|INR)(?:\\s*)([0-9,]+(?:\\.[0-9]+)?|\\.[0-9]+),\\s+curr\\s+o\\/s\\s+-\\s+(?:Rs\\.?|INR)(?:\\s*)([0-9,]+(?:\\.[0-9]+)?|\\.[0-9]+).[NOTnot]+\\s+you\\?\\s+Call\\s+\\d+.*\\s?",
    posOutstanding: 6,
    dateModified: start,
    runawayCount: 2,
    posAvailableLimit: 5,
    posMerchant: 3,
    merchantName: "",
    bankName: "HDFC",
    posAmount: 1,
    posDate: 4,
    posMerchantAcountId: 2,
    paymentType: "credit-card",
    msgType: "debit-transaction",
    txnType: "regular",
    accountType: "credit-card",
    address: "HDFCBK",
    msgSubType: "expense",
    dateCreated: start,
    posAccountId: 2,
  
  },
  {
    pattern: "(?s)\\s*ALERT:\\s*You\\'ve\\s+spent\\s+(?:Rs\\.?|INR)(?:\\s*)([0-9,]+(?:\\.[0-9]+)?|\\.[0-9]+)\\s+on\\s+[CcRrEeDdiITt]+\\s+[CaCArRdD]+\\s+([xX0-9]+)\\s+at\\s+([a-zA-Z0-9.-@\\s]+)\\s+on\\s+(\\d{4}-\\d{2}-\\d{2}:\\d{2}:\\d{2}:\\d{2}).[NOTnot]+\\s+you\\?\\s*Call\\s+\\d+.\\s*",
    posOutstanding: -1,
    dateModified: start,  
    runawayCount: 2,
    posAvailableLimit: -1,
    posMerchant: 3,
    merchantName: "",
    bankName: "HDFC",
    posAmount: 1,
    posDate: 4,
    posMerchantAcountId: 2,
    paymentType: "credit-card",
    msgType: "debit-transaction",
    txnType: "regular",
    accountType: "credit-card",
    address: "HDFCBK",
    msgSubType: "expense",
    dateCreated: start,
    posAccountId: 2,
  
  },
]